[project]
name = 'GreenEnergy-Trading'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.GreenEnergy-Trading]
path = 'contracts/GreenEnergy-Trading.clar'
clarity_version = 3
epoch = 3.1
[contracts.energy-performance-index]
path = 'contracts/energy-performance-index.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
